"""add catalog_items table

Revision ID: 4164886bde77
Revises: 1b89f463a6df
Create Date: 2026-02-19 01:45:57.403755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4164886bde77'
down_revision: Union[str, None] = '1b89f463a6df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('line', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('product_type', sa.String(), nullable=True),
    sa.Column('diameter', sa.Float(), nullable=True),
    sa.Column('diameter_body', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('show_immediately', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='Каталог товаров'
    )
    op.create_index(op.f('ix_catalog_items_category'), 'catalog_items', ['category'], unique=False)
    op.create_index(op.f('ix_catalog_items_line'), 'catalog_items', ['line'], unique=False)
    op.create_index(op.f('ix_catalog_items_sku'), 'catalog_items', ['sku'], unique=True)
    op.create_index(op.f('ix_catalog_items_subcategory'), 'catalog_items', ['subcategory'], unique=False)
    op.create_index('ix_catalog_nav', 'catalog_items', ['category', 'subcategory', 'line'], unique=False)
    op.create_index('ix_catalog_params', 'catalog_items', ['category', 'line', 'diameter', 'length'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_catalog_params', table_name='catalog_items')
    op.drop_index('ix_catalog_nav', table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_subcategory'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_sku'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_line'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_category'), table_name='catalog_items')
    op.drop_table('catalog_items')
    # ### end Alembic commands ###
